### PR TITLE
Add session 3 materials, re-render

### PR DESCRIPTION
**Pull request by dmbates**
- I have named this session 3a and will add a session 3b with a GLMM fit.
- I think we should go ahead and merge this now so the tutorial organizers can review it.
- I did the removal of "Session" in the names of the sessions and re-rendered with multiple threads for 2b.
- I also ran the files through JuliaFormatter to provide consistent spacing, etc.

### CODE REVIEW

**Review by crsl4 — APPROVED** [review]

**Review by crsl4 — APPROVED** [review]

**Comment by crsl4** [comment]
Let me know if this is ready for squash and merge (or other merging option). Thanks!

**Comment by dmbates** [comment]
Yes, good to merge. Please do so (or I can, if you prefer).

**Comment by dmbates** [comment]
Thanks for doing that, @crsl4.  I find that the site at https://crsl4.github.io/julia-workshop still delivers an old version without section 3 but if I checkout the main branch of the repository and run `quarto preview` I get the most recent version with sections 3a and 3b.  How about for you - does the latest version with sections 3a and 3b appear on the web site for you?

**Comment by dmbates** [comment]
Hmm, it seems the files are there but the links in the other pages aren't.  So the "next page" link at the bottom of session2b links to `session3-linear-mixed-effects.html`, which doesn't exist but if I open the page https://crsl4.github.io/julia-workshop/session3a-linear-mixed-effects.html explicitly I get the expected content without the figures.  It seems that I may have problems with some caches along the path from my network to github.io not flushing out-of-date pages.

**Comment by crsl4** [comment]
No, I do not see session 3 in the website. Maybe it will take a little bit?

**Comment by dmbates** [comment]
Yes, I think it was due to some of the web page caches between my home network and github - likely my internet provider - not being updated.  I get the text and figures for 3b although still only the text for 3a.

**Pull request merged**
