### PR TITLE
Update phrasings and location of image files.

### PR DESCRIPTION
**Pull request by dmbates**
- add `pics` directory containing image files
- change session5 to render as html, not reveal.js
- correct a dead link in session4
- remove jupyter info in YAML headers of `.qmd` files that do not have code chunks so that rendering is much faster
- add navigation to `_quarto.yml`
- add `.JuliaFormatter` and format directory
- tweaks of session2 sources

### CODE REVIEW

**Comment by dmbates** [comment]
@crsl4 I hope the move went well.  No rush on this - it is just some cleanup.  I haven't committed changes to `Manifest.toml` because I am waiting for `RangeTrees.jl` to be [registered](https://github.com/JuliaRegistries/General/pull/62511).

**Comment by dmbates** [comment]
@crsl4 The session2b sources use the code in the "recursivenode" branch of [RangeTrees.jl](https://github.com/dmbates/RangeTrees.jl).  Once RangeTrees.jl is in the registry I will merge the recursivenode branch and release a new version.  That should happen on Monday I hope, so you may want to wait until then to look at this PR.

**Comment by crsl4** [comment]
Thanks! Let me know once RangeTrees is in the registry to check the PR and merge!

**Comment by dmbates** [comment]
@crsl4 `RangeTrees.jl` is now registered so when you have time please take a look at this.  For some reason the benchmarks in session2b have fallen off a cliff on my computer and I can't decide why that is happening.  What has been as fast as 1/3 sec for obtaining coverage of all the `rnarangevecs` is now taking 1.2 sec and I don't know why.  I am using a very recent version of quarto-cli which may have something to do with it, I'm not sure.

**Comment by dmbates** [comment]
@crsl4 The conflicting files Project.toml and Manifest.toml can be resolved.  I added a compat segment for RangeTrees in `Project.toml` in the main branch at 0.2 then went to this branch and made it 0.3, which is what it should be.  But I forgot to merge the change in the main branch into this branch before committing.

**Review by crsl4 — APPROVED** [review]

**Pull request merged**
